### ISSUE TITLE
Bug in workflow stops deployment

### ISSUE THREAD

**Issue by spydmobile** [WISE-Developers/wise_docs#3]
https://github.com/WISE-Developers/wise_docs/blob/d6f9c754cd0d99598ac280082c1db2f3bfe71901/.github/workflows/main.yml#L28

May just be outdated, or may require security modifications as per:
https://github.com/appleboy/ssh-action/issues/104

the error is here:
https://github.com/WISE-Developers/wise_docs/actions/runs/4166678227/jobs/7211313388#step:6:89

**Comment by enghitalo** [comment]
Some update?

**Comment by spydmobile** [comment]
found and fixed.

**Comment by enghitalo** [comment]
> found and fixed.

Can you show me the fixed code/PR?

**Comment by spydmobile** [comment]
it was not code, it was an expired PAT. the application is now building again.
